version: '3.8'

services:
  traefik:
    image: traefik:v2.10.7
    container_name: workbench-proxy
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "10000:10000"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  hybrid-rag:
    image: project-hybrid-rag:latest
    container_name: hybrid-rag
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hybrid-rag.rule=Host(`localhost`)"
      - "traefik.http.routers.hybrid-rag.entrypoints=web"
    restart: unless-stopped

networks:
  default:
    name: lacham378-workbench-hybrid-rag_default
