entryPoints:
  web:
    address: ":80"

  dashboard:
    address: ":8080"

api:
  dashboard: true
  insecure: true  # Only for development — disable in production

log:
  level: INFO

providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
